server:
  port: 1000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/products/**

        - id: order-service
          uri: http://localhost:9094
          predicates:
            - Path=/api/v1/orders/**

        - id: inventory-service
          uri: http://localhost:9093
          predicates:
            - Path=/api/v1/inventory/**

        - id: auth-service
          uri: http://localhost:9092
          predicates:
            - Path=/api/v1/auth/**
